import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';
import { areaValidator, subAreaValidator } from './lib/agentAreas';

export default defineSchema({
  users: defineTable({ email: v.string(), walletAddress: v.optional(v.string()), createdAt: v.string() }).index('by_email', ['email']),
  organizations: defineTable({ name: v.string(), slug: v.string(), createdAt: v.string() }).index('by_slug', ['slug']),
  memberships: defineTable({ userId: v.id('users'), organizationId: v.id('organizations'), role: v.union(v.literal('owner'), v.literal('admin'), v.literal('operator'), v.literal('viewer')) }).index('by_org_user', ['organizationId', 'userId']),
  agents: defineTable({
    organizationId: v.id('organizations'),
    name: v.string(),
    status: v.union(v.literal('active'), v.literal('paused')),
    createdAt: v.string(),
    chatId: v.optional(v.id('chats')),
    area: v.optional(areaValidator),
    subArea: subAreaValidator,
  }).index('by_org', ['organizationId']).index('by_chat', ['chatId']).index('by_org_area', ['organizationId', 'area']),
  orchestrationSessions: defineTable({
    organizationId: v.id('organizations'),
    chatId: v.id('chats'),
    status: v.union(
      v.literal('queued'),
      v.literal('spawning'),
      v.literal('active'),
      v.literal('failed'),
      v.literal('completed')
    ),
    spawnRequestId: v.optional(v.string()),
    vpsRef: v.optional(v.string()),
    containerRef: v.optional(v.string()),
    error: v.optional(v.string()),
    createdAt: v.string(),
    updatedAt: v.string(),
  })
    .index('by_chat', ['chatId'])
    .index('by_org_updatedAt', ['organizationId', 'updatedAt']),
  orchestrationAgents: defineTable({
    sessionId: v.id('orchestrationSessions'),
    agentKey: v.string(),
    parentAgentKey: v.optional(v.string()),
    name: v.string(),
    role: v.optional(v.string()),
    status: v.union(
      v.literal('spawning'),
      v.literal('idle'),
      v.literal('working'),
      v.literal('blocked'),
      v.literal('completed'),
      v.literal('error')
    ),
    x: v.optional(v.number()),
    y: v.optional(v.number()),
    meta: v.optional(v.any()),
    createdAt: v.string(),
    updatedAt: v.string(),
  })
    .index('by_session', ['sessionId'])
    .index('by_session_agentKey', ['sessionId', 'agentKey']),
  orchestrationEvents: defineTable({
    sessionId: v.id('orchestrationSessions'),
    type: v.string(),
    payload: v.optional(v.any()),
    createdAt: v.string(),
  }).index('by_session', ['sessionId']),
  founderIdeas: defineTable({
    organizationId: v.id('organizations'),
    founderUserId: v.optional(v.id('users')),
    title: v.string(),
    ideaText: v.string(),
    targetUser: v.optional(v.string()),
    problem: v.optional(v.string()),
    monetizationPreference: v.optional(v.string()),
    businessModelPreference: v.optional(v.string()),
    desiredAutomationLevel: v.optional(v.string()),
    skillsResources: v.optional(v.string()),
    timeAvailable: v.optional(v.string()),
    country: v.optional(v.string()),
    language: v.optional(v.string()),
    channelPreferences: v.optional(v.array(v.string())),
    riskTolerance: v.optional(v.string()),
    status: v.union(
      v.literal('draft'),
      v.literal('briefing'),
      v.literal('optioning'),
      v.literal('routed'),
      v.literal('blueprinted'),
      v.literal('ignition_ready'),
      v.literal('launched')
    ),
    createdAt: v.string(),
    updatedAt: v.string(),
  }).index('by_org_updatedAt', ['organizationId', 'updatedAt']),
  founderBriefs: defineTable({
    ideaId: v.id('founderIdeas'),
    businessSummary: v.string(),
    clarifiedProblem: v.string(),
    targetCustomer: v.string(),
    likelyOfferType: v.string(),
    likelyRevenuePath: v.string(),
    constraints: v.array(v.string()),
    recommendedLaunchPosture: v.string(),
    uncertaintyFlags: v.array(v.string()),
    rawOutput: v.optional(v.string()),
    promptVersion: v.optional(v.string()),
    createdAt: v.string(),
    updatedAt: v.string(),
  }).index('by_idea', ['ideaId']),
  companyOptions: defineTable({
    ideaId: v.id('founderIdeas'),
    profile: v.union(v.literal('conservative'), v.literal('balanced'), v.literal('ambitious')),
    optionKey: v.string(),
    name: v.string(),
    businessThesis: v.string(),
    offer: v.string(),
    targetUser: v.string(),
    revenuePath: v.string(),
    minimumCompanyStructure: v.array(v.string()),
    minimumAgentStructure: v.array(v.string()),
    complexityScore: v.number(),
    recommendedLaunchMotion: v.string(),
    fitReason: v.string(),
    rawOutput: v.optional(v.string()),
    promptVersion: v.optional(v.string()),
    createdAt: v.string(),
  }).index('by_idea', ['ideaId']),
  selectedRoutes: defineTable({
    ideaId: v.id('founderIdeas'),
    selectedOptionKey: v.string(),
    selectedProfile: v.union(v.literal('conservative'), v.literal('balanced'), v.literal('ambitious')),
    rationale: v.optional(v.string()),
    selectedByUserId: v.optional(v.id('users')),
    createdAt: v.string(),
  }).index('by_idea', ['ideaId']),
  companyBlueprints: defineTable({
    ideaId: v.id('founderIdeas'),
    routeId: v.id('selectedRoutes'),
    version: v.number(),
    selectedCompanyStructure: v.array(v.string()),
    coreAgents: v.array(v.string()),
    subAgents: v.array(v.string()),
    workflows: v.array(v.string()),
    approvalsNeeded: v.array(v.string()),
    memoryRequirements: v.array(v.string()),
    toolRequirements: v.array(v.string()),
    kpis: v.array(v.string()),
    ignitionPromptInput: v.any(),
    rawOutput: v.optional(v.string()),
    promptVersion: v.optional(v.string()),
    createdAt: v.string(),
  }).index('by_idea', ['ideaId']),
  ignitionConfigs: defineTable({
    blueprintId: v.id('companyBlueprints'),
    prompt: v.string(),
    config: v.any(),
    model: v.optional(v.union(v.literal('codex'), v.literal('opus'), v.literal('venice'))),
    createdAt: v.string(),
    updatedAt: v.string(),
  }).index('by_blueprint', ['blueprintId']),
  deploymentJobs: defineTable({
    organizationId: v.id('organizations'),
    ideaId: v.id('founderIdeas'),
    blueprintId: v.id('companyBlueprints'),
    orchestrationSessionId: v.optional(v.id('orchestrationSessions')),
    status: v.union(
      v.literal('draft'),
      v.literal('ready_to_deploy'),
      v.literal('deploying'),
      v.literal('deployed'),
      v.literal('failed'),
      v.literal('queued'),
      v.literal('running'),
      v.literal('succeeded'),
      v.literal('cancelled')
    ),
    provider: v.optional(v.string()),
    target: v.optional(v.string()),
    externalDeploymentId: v.optional(v.string()),
    callbackSecretRef: v.optional(v.string()),
    error: v.optional(v.string()),
    createdAt: v.string(),
    updatedAt: v.string(),
  })
    .index('by_org_updatedAt', ['organizationId', 'updatedAt'])
    .index('by_idea', ['ideaId'])
    .index('by_session', ['orchestrationSessionId']),
  runtimeInstances: defineTable({
    jobId: v.id('deploymentJobs'),
    environment: v.union(v.literal('staging'), v.literal('production')),
    status: v.union(v.literal('starting'), v.literal('healthy'), v.literal('degraded'), v.literal('stopped'), v.literal('failed')),
    endpointUrl: v.optional(v.string()),
    vpsRef: v.optional(v.string()),
    containerRef: v.optional(v.string()),
    lastHeartbeatAt: v.optional(v.string()),
    createdAt: v.string(),
    updatedAt: v.string(),
  }).index('by_job', ['jobId']),
  agentEvents: defineTable({
    organizationId: v.id('organizations'),
    sessionId: v.optional(v.id('orchestrationSessions')),
    deploymentJobId: v.optional(v.id('deploymentJobs')),
    runtimeInstanceId: v.optional(v.id('runtimeInstances')),
    agentKey: v.optional(v.string()),
    level: v.union(v.literal('info'), v.literal('warn'), v.literal('error')),
    type: v.string(),
    message: v.string(),
    payload: v.optional(v.any()),
    createdAt: v.string(),
  })
    .index('by_org_time', ['organizationId', 'createdAt'])
    .index('by_session', ['sessionId']),
  agentRuns: defineTable({ organizationId: v.id('organizations'), agentId: v.id('agents'), taskId: v.optional(v.id('tasks')), status: v.union(v.literal('queued'), v.literal('running'), v.literal('success'), v.literal('failed')), createdAt: v.string() }).index('by_agent', ['agentId']),
  tasks: defineTable({ organizationId: v.id('organizations'), title: v.string(), status: v.union(v.literal('todo'), v.literal('in_progress'), v.literal('done')), priority: v.union(v.literal('low'), v.literal('medium'), v.literal('high')), assigneeAgentId: v.optional(v.id('agents')), createdAt: v.string() }).index('by_org_status', ['organizationId', 'status']),
  taskEvents: defineTable({ taskId: v.id('tasks'), type: v.string(), payload: v.optional(v.any()), createdAt: v.string() }).index('by_task', ['taskId']),
  chats: defineTable({
    organizationId: v.optional(v.id('organizations')),
    title: v.string(),
    createdAt: v.string(),
    updatedAt: v.string(),
    agentId: v.optional(v.id('agents')),
    summary: v.optional(v.string()),
    summaryUpdatedAt: v.optional(v.string()),
  }).index('by_org', ['organizationId']).index('by_updatedAt', ['updatedAt']).index('by_agent', ['agentId']),
  messages: defineTable({ chatId: v.id('chats'), authorType: v.union(v.literal('human'), v.literal('agent')), authorId: v.string(), content: v.string(), createdAt: v.string() }).index('by_chat', ['chatId']),
  wallets: defineTable({ organizationId: v.id('organizations'), ownerUserId: v.id('users'), provider: v.string(), address: v.string(), createdAt: v.string() }).index('by_org', ['organizationId']),
  walletPermissions: defineTable({ walletId: v.id('wallets'), memberUserId: v.id('users'), permission: v.union(v.literal('view'), v.literal('propose'), v.literal('execute'), v.literal('approve')), createdAt: v.string() }).index('by_wallet_user', ['walletId', 'memberUserId']),
  approvals: defineTable({
    organizationId: v.id('organizations'),
    resourceType: v.string(),
    resourceId: v.string(),
    requestedBy: v.id('users'),
    status: v.union(v.literal('pending'), v.literal('approved'), v.literal('rejected')),
    ideaId: v.optional(v.id('founderIdeas')),
    jobId: v.optional(v.id('deploymentJobs')),
    reason: v.optional(v.string()),
    decisionAt: v.optional(v.string()),
    createdAt: v.string(),
  }).index('by_org_status', ['organizationId', 'status']),
  auditLogs: defineTable({ organizationId: v.id('organizations'), actorUserId: v.optional(v.id('users')), action: v.string(), resourceType: v.string(), resourceId: v.optional(v.string()), metadata: v.optional(v.any()), createdAt: v.string() }).index('by_org_time', ['organizationId', 'createdAt'])
});
